version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo "Sucessfully"
      - run:
          name: Running in a Unique Container
          command: |
            node -v