version: 2.0
jobs:
  build:
    working_directory: ~/Web-server
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: output list file
          command: |
            pwd
            ls -al
      - run:
          name: Testing
          command: |
            python3 manage.py test moviepoll
      - run:
          name: Runserver
          command: |
            python3 manage.py runserver
